NOT = "-"
RULE_SEPARATOR = " :- "
WORD_SEPARATOR = "_"

INCOMPATIBLE_UPDATE = "incompatible" + WORD_SEPARATOR + "update"
ACTION_UPDATE_NAME = "update"
UPDATING = "updating"
INS = "ins" + WORD_SEPARATOR
DEL = "del" + WORD_SEPARATOR
REQUEST = WORD_SEPARATOR + "request"
CLOSURE = WORD_SEPARATOR + "closure"
